# LOCALHOST

###
GET http://localhost:3200/exerciseTypes

###
POST http://localhost:3200/exerciseTypes HTTP/1.1
content-type: application/json

{
   "type": "Dumbbell rows"
}

###
PUT http://localhost:3200/exerciseTypes/649522ec4c97636427453f78 HTTP/1.1
content-type: application/json

{
   "type": "DUMBBELL ROWS"
}

###
GET http://localhost:3200/exerciseTypes/649522ec4c97636427453f78

###
DELETE http://localhost:3200/exerciseTypes/649522ec4c97636427453f78 HTTP/1.1
content-type: application/json

###
GET http://localhost:3200/exercises

###
POST http://localhost:3200/exercises HTTP/1.1
content-type: application/json

{
    "name": "dumbbell rows",
    "sets": 3,
    "reps": 15
}

###
PUT http://localhost:3200/exercises/649523654c97636427453f79 HTTP/1.1
content-type: application/json

{
    "name": "dumbbell rows",
    "sets": 3,
    "reps": 18
}

###
GET http://localhost:3200/exercises/649523654c97636427453f79

###
DELETE http://localhost:3200/exercises/649523654c97636427453f79 HTTP/1.1
content-type: application/json

###
GET http://localhost:3200/workouts

###
POST http://localhost:3200/workouts HTTP/1.1
content-type: application/json

{
    "startTime": "2023-06-23T03:57:00.188Z",
    "endTime": "2023-06-23T04:27:00.188Z",
    "exercises": [
        {
            "name": "dumbbell rows",
            "sets": 3,
            "reps": 15
        },
        {
            "name": "Squats",
            "sets": 2,
            "reps": 10
        }
    ]
}

###
GET http://localhost:3200/workouts/649523e64c97636427453f7a

###
PUT http://localhost:3200/workouts/649523e64c97636427453f7a HTTP/1.1
content-type: application/json

{
    "startTime": "2023-06-23T03:57:00.188Z",
    "endTime": "2023-06-23T04:47:00.188Z",
    "exercises": [
        {
            "name": "dumbbell rows",
            "sets": 5,
            "reps": 15
        },
        {
            "name": "Squats",
            "sets": 2,
            "reps": 10
        }
    ]
}

###
DELETE https://cse341-workout-tracker.onrender.com/workouts/649523e64c97636427453f7a HTTP/1.1
content-type: application/json

# PRODUCTION

###
GET https://cse341-workout-tracker.onrender.com/exerciseTypes

###
POST https://cse341-workout-tracker.onrender.com/exerciseTypes HTTP/1.1
content-type: application/json

{
   "type": "Dumbbell rows"
}

###
PUT https://cse341-workout-tracker.onrender.com/exerciseTypes/649522ec4c97636427453f78 HTTP/1.1
content-type: application/json

{
   "type": "DUMBBELL ROWS"
}

###
GET https://cse341-workout-tracker.onrender.com/exerciseTypes/649522ec4c97636427453f78

###
DELETE https://cse341-workout-tracker.onrender.com/exerciseTypes/649522ec4c97636427453f78 HTTP/1.1
content-type: application/json

###
GET https://cse341-workout-tracker.onrender.com/exercises

###
POST https://cse341-workout-tracker.onrender.com/exercises HTTP/1.1
content-type: application/json

{
    "name": "dumbbell rows",
    "sets": 3,
    "reps": 15
}

###
PUT https://cse341-workout-tracker.onrender.com/exercises/649523654c97636427453f79 HTTP/1.1
content-type: application/json

{
    "name": "dumbbell rows",
    "sets": 3,
    "reps": 18
}

###
GET https://cse341-workout-tracker.onrender.com/exercises/649523654c97636427453f79

###
DELETE https://cse341-workout-tracker.onrender.com/exercises/649523654c97636427453f79 HTTP/1.1
content-type: application/json

###
GET https://cse341-workout-tracker.onrender.com/workouts

###
POST https://cse341-workout-tracker.onrender.com/workouts HTTP/1.1
content-type: application/json

{
    "startTime": "2023-06-23T03:57:00.188Z",
    "endTime": "2023-06-23T04:27:00.188Z",
    "exercises": [
        {
            "name": "dumbbell rows",
            "sets": 3,
            "reps": 15
        },
        {
            "name": "Squats",
            "sets": 2,
            "reps": 10
        }
    ]
}

###
GET https://cse341-workout-tracker.onrender.com/workouts/649523e64c97636427453f7a

###
PUT https://cse341-workout-tracker.onrender.com/workouts/649523e64c97636427453f7a HTTP/1.1
content-type: application/json

{
    "startTime": "2023-06-23T03:57:00.188Z",
    "endTime": "2023-06-23T04:47:00.188Z",
    "exercises": [
        {
            "name": "dumbbell rows",
            "sets": 5,
            "reps": 15
        },
        {
            "name": "Squats",
            "sets": 2,
            "reps": 10
        }
    ]
}

###
DELETE https://cse341-workout-tracker.onrender.com/workouts/649523e64c97636427453f7a HTTP/1.1
content-type: application/json